"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowRight, Check, ChevronRight, FileText, Home, KeyRound, LoaderCircle, LockKeyhole, LogOut, RefreshCw, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { Connection, CreditDetail } from "@/lib/types";
import { registerCreditRead } from "./webmcp";
import DocumentWorkspace from "./document-workspace";
import { portalApi as api } from "./portal-api";

const stages = ["Prospecção", "Análise de crédito", "Avaliação do imóvel", "Análise de documentos", "Emissão do contrato", "Contrato registrado"];
const money = (v: number | null) => v === null ? "Não informado" : new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(v);
export default function CreditApp({onSignOut}:{onSignOut:()=>void}) {
  const [connection,setConnection] = useState<Connection>({state:"disconnected"});
  const [checking,setChecking] = useState(true), [busy,setBusy] = useState(false), [error,setError] = useState(""), [signIn,setSignIn] = useState(false);
  const [selected,setSelected] = useState(""), [detail,setDetail] = useState<CreditDetail|null>(null), [tab,setTab] = useState("overview"), [search,setSearch] = useState("");
  const generation = useRef(0);
  const proposal = connection.proposals?.find(p=>p.id===selected);
  const viewRef=useRef({connection,detail,selected,tab});
  useEffect(()=>{viewRef.current={connection,detail,selected,tab};},[connection,detail,selected,tab]);
  useEffect(()=>registerCreditRead(()=>viewRef.current),[]);
  const handleError = useCallback((e:unknown)=>{const err=e as Error & {status?:number};setError(err.message||"Não foi possível conectar. Tente novamente.");if(err.status===401)setSignIn(true);if(err.status===428){setConnection({state:"disconnected"});setDetail(null);setSelected("");}},[]);
  const refresh = useCallback(async()=>{setBusy(true);setError("");try{const result=await api<Connection>("session");setConnection(result);if(result.state==="connected")setSelected(current=>result.proposals?.some(p=>p.id===current)?current:result.proposals?.[0]?.id||"");else{setDetail(null);setSelected("");}}catch(e){handleError(e);}finally{setChecking(false);setBusy(false);}},[handleError]);
  useEffect(()=>{void refresh();},[refresh]);
  useEffect(()=>{const current=++generation.current;if(!selected||connection.state!=="connected")return;setDetail(null);setBusy(true);setSearch("");api<CreditDetail>("detail",{proposalId:selected}).then(data=>{if(current===generation.current)setDetail(data);}).catch(e=>{if(current===generation.current)handleError(e);}).finally(()=>{if(current===generation.current)setBusy(false);});return()=>{generation.current++;};},[selected,connection,handleError]);
  async function connect(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=event.currentTarget,fields=new FormData(form);const body=connection.state==="code"?{code:String(fields.get("code")||"")}:{username:String(fields.get("username")||""),password:String(fields.get("password")||"")};try{const result=await api<Connection>(connection.state==="code"?"verify":"login",body);form.reset();setConnection(result);if(result.state==="connected")await refresh();}catch(e){handleError(e);if("password" in body){const input=form.elements.namedItem("password") as HTMLInputElement;if(input)input.value="";}}finally{setBusy(false);}}
  async function disconnect(){setBusy(true);setError("");++generation.current;try{await api("disconnect",{});setConnection({state:"disconnected"});setDetail(null);setSelected("");setTab("overview");}catch(e){handleError(e);}finally{setBusy(false);}}
  const connected=connection.state==="connected";
  const docs=detail?.documents.filter(d=>`${d.type} ${d.description}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR")))||[];
  return <div className="credit-shell">
    <aside className="sidebar"><a href="/" className="brand"><span className="brand-icon"><Home size={24}/></span><span>Meu crédito<small>FUNCHAL</small></span></a><div className="sidebar-label">CRÉDITO IMOBILIÁRIO</div><nav aria-label="Navegação principal">{[{id:"overview",label:"Visão geral",Icon:Home},{id:"documents",label:"Documentos",Icon:FileText},{id:"history",label:"Histórico",Icon:RefreshCw}].map(({id,label,Icon})=><button key={id} disabled={busy} onClick={()=>setTab(id)} aria-current={tab===id?"page":undefined}><Icon size={20}/><span>{label}</span>{id==="documents"&&detail&&<b>{detail.documents.length}</b>}</button>)}</nav><div className="sidebar-bottom"><ShieldCheck size={22}/><p>Acesso privado<small>Dados consultados no portal Funchal</small></p></div></aside>
    <div className="main-wrap"><header className="topbar"><span className="mobile-brand"><Home size={20}/> Meu crédito</span><span className="desktop-crumb">Funchal <ChevronRight size={15}/> Acompanhamento</span><div className="top-actions"><button className="auth-signout" disabled={busy} onClick={async()=>{await disconnect();onSignOut();}}>Sair da conta</button><span className="private-label"><LockKeyhole size={15}/> Privado</span>{connected&&<button disabled={busy} onClick={disconnect} className="icon-button" aria-label="Desconectar do portal"><LogOut size={20}/></button>}</div></header>
    <main className="workspace"><div className="page-heading"><div><p className="eyebrow">SEU FINANCIAMENTO</p><h1>{tab==="documents"?"Documentos":tab==="history"?"Histórico da proposta":"Cada etapa, mais perto de casa."}</h1><p>{connected?"Acompanhe as informações disponíveis no portal Funchal.":"Entre para acompanhar seu crédito imobiliário Bradesco."}</p></div>{connected&&<Button variant="outline" disabled={busy} onClick={refresh}><RefreshCw className={busy?"spin":""} size={17}/>Atualizar</Button>}</div>
    {error&&<div className="notice error" role="alert">{error}{signIn&&<button className="text-button" onClick={onSignOut}>Entrar novamente com Google <ArrowRight size={16}/></button>}</div>}
    {checking?<div className="loading-state" role="status"><LoaderCircle className="spin"/> Verificando sua conexão…</div>:!connected?<section className="connection-grid"><div className="connection-card"><span className="connection-icon">{connection.state==="code"?<KeyRound size={27}/>:<LockKeyhole size={27}/>}</span><p className="eyebrow">{connection.state==="code"?"CONFIRMAÇÃO DE ACESSO":"CONECTAR AO PORTAL"}</p><h2>{connection.state==="code"?"Confira seu código":"Seu acompanhamento começa aqui"}</h2><p>{connection.state==="code"?connection.message||"Digite o código de autenticação enviado pelo portal.":"Use o mesmo usuário e senha do portal Funchal. O código de autenticação será solicitado na próxima etapa."}</p>
    {!signIn&&<form onSubmit={connect} key={connection.state}>{connection.state==="code"?<label htmlFor="code">Código de autenticação<Input id="code" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} required autoFocus placeholder="000000" className="code-input"/></label>:<><label htmlFor="username">Usuário do portal<Input id="username" name="username" autoComplete="username" autoCapitalize="none" spellCheck={false} maxLength={150} required placeholder="Seu usuário Funchal"/></label><label htmlFor="password">Senha<Input id="password" name="password" type="password" autoComplete="current-password" maxLength={200} required placeholder="Sua senha do portal"/></label></>}<Button type="submit" className="connect-button" disabled={busy}>{busy?<><LoaderCircle className="spin" size={19}/> Conectando…</>:<>{connection.state==="code"?"Validar código":"Continuar"}<ArrowRight size={19}/></>}</Button>{connection.state==="code"&&<button className="text-button" type="button" disabled={busy} onClick={disconnect}>Voltar e solicitar outro código</button>}</form>}
    <div className="connection-note"><ShieldCheck size={19}/><p>A senha e o código são usados apenas para entrar no portal e não são armazenados. A sessão fica protegida e expira automaticamente.</p></div></div><div className="journey-intro"><p className="eyebrow">DO PRIMEIRO PASSO ÀS CHAVES</p><h2>Seu crédito.<br/>Uma etapa de cada vez.</h2><ol>{stages.map((stage,i)=><li key={stage}><span>{String(i+1).padStart(2,"0")}</span>{stage}</li>)}</ol><p className="muted">A etapa atual aparecerá após você conectar sua conta.</p></div></section>:<>
    {connection.proposals?.length?<div className="proposal-bar"><div><span className="eyebrow">PROPOSTA</span>{connection.proposals.length>1?<select aria-label="Selecionar proposta" value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}>{connection.proposals.map(p=><option key={p.id} value={p.id}>{p.number} · {p.name}</option>)}</select>:<strong>{proposal?.number||"Sem número"} <span>· {proposal?.name}</span></strong>}</div><span className="source-label">Bradesco · Funchal</span></div>:<div className="empty"><Home size={30}/><h2>Nenhuma proposta disponível</h2><p>O portal não retornou propostas para este acesso.</p></div>}
    {proposal&&<>{tab==="overview"&&<><section className="status-card" aria-busy={busy}><div className="status-main"><div className="status-kicker"><span className="stage-mark">{detail?.stage?String(Math.min(detail.stage,6)).padStart(2,"0"):"—"}</span><span>{detail?.stage?detail.stage>6?"FLUXO CONCLUÍDO":`ETAPA ${detail.stage} DE 6`:"ANDAMENTO DA PROPOSTA"}</span></div><h2>{detail?detail.stage?stages[Math.min(detail.stage,6)-1]:"Etapa não informada":"Consultando andamento…"}</h2><p>{detail?.status||(busy?"Buscando as informações mais recentes no portal.":"O portal não informou a situação atual.")}</p></div><div className="status-footer"><span><RefreshCw size={15}/>{detail?`Consultado às ${new Date(detail.updatedAt).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}`:"Consulta em andamento"}</span><span>Informações do portal</span></div></section><section className="metrics" aria-label="Resumo do financiamento"><Metric label="Valor do financiamento" value={money(proposal.amount)}/><Metric label="Prazo" value={proposal.months?`${proposal.months} meses`:"Não informado"}/><Metric label="Data do protocolo" value={proposal.date||"Não informada"}/></section><section className="panel"><div className="section-heading"><h2>Jornada do financiamento</h2><span>6 etapas</span></div><ol className="stage-timeline">{stages.map((stage,i)=><li key={stage} className={detail?.stage?detail.stage>i+1?"complete":detail.stage===i+1?"current":"":""} aria-current={detail?.stage===i+1?"step":undefined}><span className="step-icon">{detail?.stage&&detail.stage>i+1?<Check size={16}/>:i+1}</span><div><strong>{stage}</strong><small>{detail?.stage?detail.stage>i+1?"Concluída":detail.stage===i+1?"Etapa atual":"Próxima etapa":"Aguardando informação"}</small></div></li>)}</ol></section><div className="overview-bottom"><button className="document-shortcut" disabled={busy} onClick={()=>setTab("documents")}><span className="doc-icon"><FileText size={24}/></span><span><strong>Seus documentos</strong><small>{detail?`${detail.documents.length} disponíveis para consulta`:"Consultando documentos"}</small></span><ChevronRight size={20}/></button><div className="contract-summary"><span className="eyebrow">OPERAÇÃO</span><strong>{proposal.operation||"Não informada"}</strong><span>Contrato: {proposal.contract||"Ainda não informado"}</span></div></div></>}
    {tab==="documents"&&<DocumentWorkspace key={selected} proposalId={selected} proposalNumber={proposal.number} detail={detail} busy={busy} setBusy={setBusy} onDetail={setDetail} onError={handleError}/>}
    {tab==="history"&&<section className="panel"><div className="section-heading"><h2>Atualizações da proposta</h2></div>{!detail?<div className="loading-state"><LoaderCircle className="spin"/> Consultando histórico…</div>:!detail.historyAllowed?<div className="empty"><LockKeyhole size={30}/><h3>Histórico não disponibilizado</h3><p>O portal não habilitou o histórico para este acesso.</p></div>:!detail.history.length?<div className="empty"><RefreshCw size={30}/><h3>Nenhuma atualização disponível</h3><p>Novos registros aparecerão aqui quando retornados pelo portal.</p></div>:<ol className="history-list">{detail.history.map((h,i)=><li key={i}><time>{h.date}</time><p>{h.text}</p><small>{h.author}</small></li>)}</ol>}</section>}</>}
    </>}
    <footer className="page-footer"><span><LockKeyhole size={14}/> Seu acompanhamento privado</span><span>Dados do portal Funchal</span></footer></main></div>
  </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>;}

